### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by umair-rao** [umair-rao/Kanban-board#21]
We are two people in the JavaScript Capstone project.

Project Link: https://github.com/umair-rao/Kanban-board/projects/1

by @umair-rao and @Ibtisam34

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [x] Kindly make sure to add tasks in the kanban board of the features you are to implement. This means that you need to add all of the "issues" you've created as cards in the kanban board. As per [these](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Make%20sure%20that,in%20the%20title.) requirements.
- [x] Please make sure that each task is assigned to a team member where eventually all tasks should be assigned equally between all team members, as per [this](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the%20team%20members%20should%20assign%20themselves%20to%20the%20correct%20cards.%20Decide%20who%20will%20be%20the%20assignee%20for%20the%20cards%20marked%20as%20group%20tasks.%20All%20cards%20on%20your%20Kanban%20board%20should%20have%20assignees.) requirement.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by umair-rao** [comment]
- Tasks added in Kanban Board.
 - All the tasks are assigned equally between partners.

**Comment by Alfredbis29** [comment]
## Hello @ShadyShawkat  ,
 I'm Alfred your reviewer for this PR :man_beard:
 
 Great work working on your project so far! :clap: There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ![](https://camo.githubusercontent.com/4f9601b422a77702aefe8e13485d2d5618cc0c30772eb2aa9f4129eac4757e06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966) 
 
 ##  Required Changes :black_circle: 
 

- [ ] I can see that you made some changes given by the previous review but you forget to assign tasks to each member of the group and time the task should take , kindly fix this for your kaban board to match all requirements :wink: 
 
 ## [Optional] suggestions
 

- [ ]  N/A

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 Cheers and Happy coding! :partying_face: :clap: :clap:

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me  in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
> We are two people in the JavaScript Capstone project.
> 
> Project Link: https://github.com/umair-rao/Kanban-board/projects/1
> 
> by @umair-rao and @Ibtisam34

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Kanban Board ✅ 
- Distribution of task ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
